image:
  name: hashicorp/terraform:0.12.19
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
- test

check terraform:
  stage: test
  only:
    refs:
    - merge_requests
  script:
  - terraform --version
  - echo "Terraform config format validation"
  - terraform fmt -check=true -recursive && echo "OK" || { echo "Failed" ; exit 1; }
  - echo "Terraform vars format validation"
  - test -f terraform.tfvars && { terraform fmt -check=true -recursive terraform.tfvars && echo "OK" || { echo "Failed" ; exit 1; }; };
  - echo "Terraform validation"
  - terraform init -backend=false
  - terraform validate && echo "OK" || { echo "Failed" ; exit 1; }
